version: '3.8'

services:

  app:
    build: .
    container_name: yuno-app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payments
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
  postgres:
    image: postgres:15
    container_name: yuno-postgres
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:              
      test: ["CMD-SHELL", "pg_isready -U user -d payments"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data   
      
  

  redis:
    image: redis:7
    container_name: yuno-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data:      
      